#!/usr/bin/env bash
# smooth
pkill -o apache2
chmod 777 /etc/nginx/nginx.conf
chown nginx:nginx -R /etc/nginx/
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
su nginx -c 'service nginx restart'
